name: updaters generator

on:
  push:
    branch: [main]
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  export-updaters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Export updaters for default sets
        run: |
          mkdir updaters
          sudo chown nobody updaters
          docker container run \
            --entrypoint clairctl \
            --rm \
            --volume $GITHUB_WORKSPACE/config/config_v4.2.2.yaml:/config/config.yaml:ro \
            --volume $GITHUB_WORKSPACE/updaters/:/updaters/:rw \
          quay.io/projectquay/clair:4.2.2 \
          export-updaters /updaters/exported-updaters

      - name: Compress updaters file
        run: gzip updaters/exported-updaters

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: updaters
          path: exported-updaters.gz
