name: updaters generator

on:
  push:
    branch: [main]

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Export updaters for default sets
        run: |
          env
          ls -la $GITHUB_WORKSPACE/config/
          ls -la $RUNNER_TEMP
          docker container run \
          --entrypoint clairctl \
          --name clair \
          --network host \
          --rm \
          --volume $GITHUB_WORKSPACE/config/config_v4.2.2.yaml:/config/config.yaml:ro \
          --volume $RUNNER_TEMP:/reports:rw \
          --workdir /run \
          quay.io/projectquay/clair:4.2.2 \
          export-updaters /reports/export-updaters
          ls -la $RUNNER_TEMP
      - name: Show updaters file
        run: head $RUNNER_TEMP/export-all-updaters
      - name: Compress updaters file
        run: tar cfz $RUNNER_TEMP/export-all-updaters.tar.gz export-updaters
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: updaters
          path: $RUNNER_TEMP/export-all-updaters.tar.gz
